# Generated by Django 4.2 on 2023-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_task_deadline_alter_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="main.tag"),
        ),
    ]
